version: '3'
services:
  h2-database:
    image: buildo/h2database
    restart: always
    container_name: "h2"
    volumes:
      - ./db:/data/db
    ports:
      - 8082:8082

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-REST-backend
    restart: on-failure
    ports:
      - '5000:5000'
    depends_on:
      - h2-database

